### ISSUE TITLE
[PE-D][Tester C] UserGuide has poor readability due to page break

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-3/tp#196] opened 2024-04-05 21:26 UTC
![image.png](https://raw.githubusercontent.com/PateShin/ped/main/files/7a989328-d13c-4cda-b457-e2a826bbd137.png)

> One part from UG

The PDF version of the User Guide has poor page breaking, which impacts readability. The expectation is that content, especially headings, bullet lists, images, and key paragraphs, should remain intact without being split across pages. The problem with poor page breaks leads to a decline in reading flow, making it difficult for users to understand.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: PateShin/ped#5

**Comment by iynixil** [comment] 2024-04-11 17:02
This is valid, and can be done.

Fix:
- Refer to [link](https://se-education.org/guides/tutorials/savingPdf.html) on how to add page breaks in markdown files
- Add page breaks before each section in the UG (after UG content has been finalized)

**Comment by tsulim** [comment] 2024-04-12 17:12
Duplicate of #182
Both are about formatting of user guide

**Closed as completed by tsulim** 2024-04-12 17:12 UTC
Labels: duplicate
