### ISSUE TITLE
[PE-D][Tester B] Able to add multiple tags with same word but different letter cases

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-3/tp#198] opened 2024-04-05 21:33 UTC
**Command Involved**
add

**Observation:**
The content for the tag is case-sensitive and multiple tags with same word but different letter cases are considered different tags.

**Steps to reproduce:**
![J.png](https://raw.githubusercontent.com/Ella-e/ped/main/files/99b6c994-e93b-4b69-865c-fda6d05f9a11.png)￼

**Rationale behind:**
Since the case difference doesn't affect the meaning of the tag, would it be more reasonable to prevent multiple tags with same word but different letter cases to be added to the system?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Ella-e/ped#7

**Comment by iynixil** [comment] 2024-04-13 06:11
This is valid, however the tagging functionality still works as intended and it is okay if user assigns tags with same names but different cases.

Fix: State in UG that tags are case-sensitive.

**Comment by whitesnowx** [comment] 2024-04-13 06:12
Addressed by #238

**Closed as completed** 2024-04-13 06:21 UTC
Labels: type.Documentation, wontfix
